### ISSUE TITLE
LethalDevMode

### ISSUE THREAD

**Issue by Giaganticevan** [FluffyFishGames/AdvancedCompany#12] opened 2024-01-25 02:16 UTC
LethalDevMode was on during advanced company. Once I turned this mod off the game was fixed
![image 1](https://github.com/FluffyFishGames/AdvancedCompany/assets/157664148/8824b7f7-1138-4875-b01c-4df6555673bc)
![image 1](https://github.com/FluffyFishGames/AdvancedCompany/assets/157664148/81e16958-16c9-4646-a278-afb80cd9de3e)

Current issues with LethalDevMode on:
Menus breaking:
Cosmetics
File
Hotbar
Graphics

**Comment by vermilionshadow-vk** [comment] 2024-01-25 03:22
To add more to the report, I'll add any of my findings from testing accordingly to format:

**Describe the bug**
The preset menus for both selecting a new save and for the AdvancedCompany settings have broken UI, little to no options can be selected. Options saved on the preset before LethalDevMode is added seems to be retained, just nothing can be edited after the fact.

**To Reproduce**
Access any save OR access the "AdvancedCompany Settings" options when both AdvancedCompany and LethalDevMode are enabled.

**Screenshots**

Preset Pages when LethalDevMode is Enabled
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/60156113/a6e5564e-0354-41e5-b3a8-beb5e4e19cd4)

A New Run with Inventory Slots set to 1000%
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/60156113/b24ff7c0-bff1-4a4a-b093-b1f89e86ead2)

The DevMode panel that appears, all functionality seems to be correct. It's just the Preset Tabs that get affected.
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/60156113/c7e6e675-25a9-4004-a571-93a522e9530a)

**Log Files**
[log.txt](https://github.com/FluffyFishGames/AdvancedCompany/files/14046353/log.txt)

The log details a brief run I did to test functionality when the two mods are enabled, the only thing affected from what I can notice is just the UI related to the Presets as mentioned earlier.

**Add a list of all your mods**
018d3ea3-11a6-dd07-7ff7-854dc81c8180

BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.136
megumin-LethalDevMode-1.0.0

**Comment by FluffyFishGames** [comment] 2024-01-29 14:48
Will be fixed in 142

**Closed by FluffyFishGames** 2024-01-29 14:48 UTC
