### ISSUE TITLE
Incompability with Huntdown

### ISSUE THREAD

**Issue by riktoi** [FluffyFishGames/AdvancedCompany#15] opened 2024-01-25 22:51 UTC
Mods in question:
Advanced Company v1.0.138
Huntdown v1.4.1

Issue:
It seems Advanced Company does not play well with Huntdown and breaks its behaviour. This is the error that pops up in console whenever it tries to spawn an enemy:
![error](https://github.com/FluffyFishGames/AdvancedCompany/assets/109578441/6bd3f53f-3b09-43f2-ae67-d5176e7b3735)

**Comment by Zuploader** [comment] 2024-01-26 07:22
This is caused by using CustomSounds, which forcefully set HideManagerGameObject to True on bepinex.cfg
Not always happening on experimentation. For testing: create new save, route to offense or any other moons

Here is a log with the error + modlist 
[huntdown + ac.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14061408/huntdown.%2B.ac.log)
List: 018d44a4-858b-ef44-d918-7b07e154027c

**Comment by Zuploader** [comment] 2024-01-26 21:19
the probleme is not directly Custom Sounds, its just one of the mods that use HideManagerGameObject for me, but mod like yippeeMod might also use this. Check your bepinex.cfg and let me know if HideManagerGameObject is on true for you

**Comment by riktoi** [comment] 2024-01-26 22:49
Ah, it is true.

Does setting this to false resolve any issues? I will mark this as resolved in that case.

**Comment by Zuploader** [comment] 2024-01-26 23:19
it does, but the weirdest thing is that if HideManager is on true and you if you have AdvancedCompany disabled, then there is no error so i think AC have an impact on this error. So leave this issue open for a bit until the mod author see it please

**Comment by riktoi** [comment] 2024-01-26 23:20
Alright. Thanks!

**Comment by FluffyFishGames** [comment] 2024-01-28 16:36
This problem should be fixed with 139.

**Closed by FluffyFishGames** 2024-01-28 16:36 UTC
